#!/usr/bin/env python3
from ipaddress import ip_address

from ocflib.infra.hosts import hosts_by_filter
from ocflib.infra.net import ipv4_to_ipv6

IPV4_DESKTOPS = '/etc/dhcp/desktop-leases.conf'
IPV6_DESKTOPS = '/etc/dhcp/desktop-leases6.conf'

desktops = hosts_by_filter('(type=desktop)')

ipv4s = []
ipv6s = []
for desktop in desktops:
    ipv4s.append('host {} {{ hardware ethernet {}; fixed-address {}; }}'.format(
        desktop['cn'][0],
        desktop['macAddress'][0],
        desktop['ipHostNumber'][0],
    ))
    ipv6s.append('host {} {{ hardware ethernet {}; fixed-address6 {}; }}'.format(
        desktop['cn'][0],
        desktop['macAddress'][0],
        ipv4_to_ipv6(ip_address(desktop['ipHostNumber'][0])),
    ))

with open(IPV4_DESKTOPS, 'w') as f:
    f.write('\n'.join(sorted(ipv4s)))

with open(IPV6_DESKTOPS, 'w') as f:
    f.write('\n'.join(sorted(ipv6s)))
